---
- name: Get running config from Cisco IOS XE router
  hosts: iosxe
  gather_facts: no
  connection: ansible.netcommon.network_cli

  tasks:
    - name: Run show running-config
      ansible.netcommon.cli_command:
        command: show running-config
      register: result

    - name: Display running config
      debug:
        msg: "{{ result.stdout }}"